version: '3.9'
services:
  sandbox-gcc-compiler:
    container_name: sandbox-gcc-compiler
    image: gcc:9.4.0
    volumes:
      - ${workspace}:/workspace
    command: ["sleep","infinity"]

  sandbox-executor:
    container_name: sandbox-executor
    image: therainisme/executor:2.0
    volumes:
      - ${workspace}:/sandbox-server/executor/workspace

  sandbox-server:
    container_name: sandbox-server
    image: therainisme/sandbox-server:2.1
    ports:
      - 7777:7777
    volumes:
      - ${workspace}:/sandbox-server/workspace
      - /var/run:/var/run
    command: ["sh", "-c", "./start -workspace ${workspace}"]
    depends_on:
      - sandbox-gcc-compiler
      - sandbox-executor