version: '3.9'
services:
  sandbox-gcc-compiler:
    container_name: sandbox-gcc-compiler
    image: gcc:9.4.0
    volumes:
      - /home/welljuly/workspace/golang/sandbox/workspace:/workspace
    command: ["sleep","infinity"]

  sandbox-executor:
    container_name: sandbox-executor
    image: therainisme/executor:1.0
    volumes:
      - /home/welljuly/workspace/golang/sandbox/workspace:/sandbox-server/executor/workspace

  sandbox-server:
    container_name: sandbox-server
    image: therainisme/sandbox-server:1.0
    ports:
      - 7777:7777
    volumes:
      - /home/welljuly/workspace/golang/sandbox/workspace:/sandbox-server/workspace
      - /var/run:/var/run
    command: ["sh", "-c", "./start -workspace /home/welljuly/workspace/golang/sandbox/workspace"]
    depends_on:
      - sandbox-gcc-compiler
      - sandbox-executor